import 'package:flutter/material.dart';

class Produto {
  final int id;
  final String titulo, imagem, descricao, marca;
  final double preco, tamanho;
  final Color cor;

  Produto({
    this.id,
    this.titulo,
    this.imagem,
    this.descricao,
    this.marca,
    this.preco,
    this.tamanho,
    this.cor,
  });
}

List<Produto> produtosMock = [
  Produto(
      imagem: 'assets/images/celuar1.png',
      cor: Colors.red,
      tamanho: 10,
      descricao: dummyText,
      titulo: 'ASDA asd',
      preco: 10000.00,
      id: 1,
      marca: 'Apple'),
  Produto(
      imagem: 'assets/images/celuar2.png',
      cor: Colors.teal,
      tamanho: 10,
      descricao: dummyText,
      titulo: 'ASDA asd',
      preco: 10000.00,
      id: 2,
      marca: 'Apple'),
  Produto(
      imagem: 'assets/images/celuar3.png',
      cor: Colors.red,
      tamanho: 10,
      descricao: dummyText,
      titulo: 'ASDA asd',
      preco: 10000.00,
      id: 3,
      marca: 'Samsumg'),
  Produto(
      imagem: 'assets/images/celuar4.png',
      cor: Colors.teal,
      tamanho: 10,
      descricao: dummyText,
      titulo: 'ASDA asd',
      preco: 10000.00,
      id: 4,
      marca: 'Xiaomi'),
  Produto(
      imagem: 'assets/images/celuar5.png',
      cor: Colors.green,
      tamanho: 10,
      descricao: dummyText,
      titulo: 'ASDA asd',
      preco: 10000.00,
      id: 5,
      marca: 'Motorola'),
  Produto(
      imagem: 'assets/images/celuar6.png',
      cor: Colors.yellow,
      tamanho: 10,
      descricao: dummyText,
      titulo: 'ASDA asd',
      preco: 10000.00,
      id: 6,
      marca: 'Nokia'),
  Produto(
      imagem: 'assets/images/celuar7.png',
      cor: Colors.amber,
      tamanho: 10,
      descricao: dummyText,
      titulo: 'ASDA asd',
      preco: 10000.00,
      id: 7,
      marca: 'Microsoft'),
  Produto(
      imagem: 'assets/images/celuar8.png',
      cor: Colors.red,
      tamanho: 10,
      descricao: dummyText,
      titulo: 'ASDA asd',
      preco: 10000.00,
      id: 8,
      marca: 'Google'),
  Produto(
      imagem: 'assets/images/celuar9.png',
      cor: Colors.amber,
      tamanho: 10,
      descricao: dummyText,
      titulo: 'ASDA asd',
      preco: 10000.00,
      id: 9,
      marca: 'Apple'),
  Produto(
      imagem: 'assets/images/celuar10.png',
      cor: Colors.green,
      tamanho: 10,
      descricao: dummyText,
      titulo: 'ASDA asd',
      preco: 10000.00,
      id: 10,
      marca: 'Apple'),
  Produto(
      imagem: 'assets/images/celuar11.png',
      cor: Colors.brown,
      tamanho: 10,
      descricao: dummyText,
      titulo: 'ASDA asd',
      preco: 10000.00,
      id: 11,
      marca: 'Samsumg'),
  Produto(
      imagem: 'assets/images/celuar12.png',
      cor: Colors.teal,
      tamanho: 10,
      descricao: dummyText,
      titulo: 'ASDA asd',
      preco: 10000.00,
      id: 12,
      marca: 'Xiaomi'),
  Produto(
      imagem: 'assets/images/celuar1.png',
      cor: Colors.green,
      tamanho: 10,
      descricao: dummyText,
      titulo: 'ASDA asd',
      preco: 10000.00,
      id: 13,
      marca: 'Motorola'),
  Produto(
      imagem: 'assets/images/celuar1.png',
      cor: Colors.yellow,
      tamanho: 10,
      descricao: dummyText,
      titulo: 'ASDA asd',
      preco: 10000.00,
      id: 14,
      marca: 'Nokia'),
  Produto(
      imagem: 'assets/images/celuar1.png',
      cor: Colors.amber,
      tamanho: 10,
      descricao: dummyText,
      titulo: 'ASDA asd',
      preco: 10000.00,
      id: 15,
      marca: 'Microsoft'),
  Produto(
      imagem: 'assets/images/celuar1.png',
      cor: Colors.red,
      tamanho: 10,
      descricao: dummyText,
      titulo: 'ASDA asd',
      preco: 10000.00,
      id: 16,
      marca: 'Google'),
  Produto(
      imagem: 'assets/images/celuar1.png',
      cor: Colors.amber,
      tamanho: 10,
      descricao: dummyText,
      titulo: 'ASDA asd',
      preco: 10000.00,
      id: 17,
      marca: 'Apple'),
  Produto(
      imagem: 'assets/images/celuar1.png',
      cor: Colors.blue,
      tamanho: 10,
      descricao: dummyText,
      titulo: 'ASDA asd',
      preco: 10000.00,
      id: 18,
      marca: 'Apple'),
  Produto(
      imagem: 'assets/images/celuar1.png',
      cor: Colors.brown,
      tamanho: 10,
      descricao: dummyText,
      titulo: 'ASDA asd',
      preco: 10000.00,
      id: 19,
      marca: 'Samsumg'),
  Produto(
      imagem: 'assets/images/celuar1.png',
      cor: Colors.teal,
      tamanho: 10,
      descricao: dummyText,
      titulo: 'ASDA asd',
      preco: 10000.00,
      id: 20,
      marca: 'Xiaomi'),
  Produto(
      imagem: 'assets/images/celuar1.png',
      cor: Colors.green,
      tamanho: 10,
      descricao: dummyText,
      titulo: 'ASDA asd',
      preco: 10000.00,
      id: 21,
      marca: 'Motorola'),
  Produto(
      imagem: 'assets/images/celuar1.png',
      cor: Colors.yellow,
      tamanho: 10,
      descricao: dummyText,
      titulo: 'ASDA asd',
      preco: 10000.00,
      id: 22,
      marca: 'Nokia'),
  Produto(
      imagem: 'assets/images/celuar1.png',
      cor: Colors.amber,
      tamanho: 10,
      descricao: dummyText,
      titulo: 'ASDA asd',
      preco: 10000.00,
      id: 23,
      marca: 'Microsoft'),
  Produto(
      imagem: 'assets/images/celuar1.png',
      cor: Colors.red,
      tamanho: 10,
      descricao: dummyText,
      titulo: 'ASDA asd',
      preco: 10000.00,
      id: 24,
      marca: 'Google'),
  Produto(
      imagem: 'assets/images/celuar1.png',
      cor: Colors.amber,
      tamanho: 10,
      descricao: dummyText,
      titulo: 'ASDA asd',
      preco: 10000.00,
      id: 25,
      marca: 'Apple'),
  Produto(
      imagem: 'assets/images/celuar1.png',
      cor: Colors.blue,
      tamanho: 10,
      descricao: dummyText,
      titulo: 'ASDA asd',
      preco: 10000.00,
      id: 26,
      marca: 'Apple'),
  Produto(
      imagem: 'assets/images/celuar1.png',
      cor: Colors.brown,
      tamanho: 10,
      descricao: dummyText,
      titulo: 'ASDA asd',
      preco: 10000.00,
      id: 27,
      marca: 'Samsumg'),
];

String dummyText =
    "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since. When an unknown printer took a galley.";
